/* Generated By:JavaCC: Do not edit this line. EBNFParserConstants.java */
package org.seaborne.bnf.parser.javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface EBNFParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LINE_COMMENT = 1;
  /** RegularExpression Id. */
  int HASH_COMMENT = 2;
  /** RegularExpression Id. */
  int WS = 3;
  /** RegularExpression Id. */
  int ASSIGN = 4;
  /** RegularExpression Id. */
  int OR = 5;
  /** RegularExpression Id. */
  int STAR = 6;
  /** RegularExpression Id. */
  int PLUS = 7;
  /** RegularExpression Id. */
  int QUERY = 8;
  /** RegularExpression Id. */
  int LPAREN = 9;
  /** RegularExpression Id. */
  int RPAREN = 10;
  /** RegularExpression Id. */
  int LBRACK = 11;
  /** RegularExpression Id. */
  int RBRACK = 12;
  /** RegularExpression Id. */
  int LBRACE = 13;
  /** RegularExpression Id. */
  int RBRACE = 14;
  /** RegularExpression Id. */
  int SEMI = 15;
  /** RegularExpression Id. */
  int DOT = 16;
  /** RegularExpression Id. */
  int NONTERMINAL = 17;
  /** RegularExpression Id. */
  int ECHAR = 18;
  /** RegularExpression Id. */
  int HEX = 19;
  /** RegularExpression Id. */
  int UCHAR = 20;
  /** RegularExpression Id. */
  int UCHAR4 = 21;
  /** RegularExpression Id. */
  int UCHAR8 = 22;
  /** RegularExpression Id. */
  int QUOTED_STRING = 23;
  /** RegularExpression Id. */
  int QSTRING1 = 24;
  /** RegularExpression Id. */
  int QSTRING2 = 25;
  /** RegularExpression Id. */
  int AZ = 26;
  /** RegularExpression Id. */
  int AZN = 27;
  /** RegularExpression Id. */
  int WORD = 28;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<LINE_COMMENT>",
    "<HASH_COMMENT>",
    "<WS>",
    "\"::=\"",
    "\"|\"",
    "\"*\"",
    "\"+\"",
    "\"?\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\".\"",
    "<NONTERMINAL>",
    "<ECHAR>",
    "<HEX>",
    "<UCHAR>",
    "<UCHAR4>",
    "<UCHAR8>",
    "<QUOTED_STRING>",
    "<QSTRING1>",
    "<QSTRING2>",
    "<AZ>",
    "<AZN>",
    "<WORD>",
  };

}
