/* Generated By:JavaCC: Do not edit this line. EBNFParserConstants.java */
package org.seaborne.bnf.parser.javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface EBNFParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LINE_COMMENT = 1;
  /** RegularExpression Id. */
  int WSP = 5;
  /** RegularExpression Id. */
  int EOL = 6;
  /** RegularExpression Id. */
  int ASSIGN = 7;
  /** RegularExpression Id. */
  int OR = 8;
  /** RegularExpression Id. */
  int STAR = 9;
  /** RegularExpression Id. */
  int PLUS = 10;
  /** RegularExpression Id. */
  int MINUS = 11;
  /** RegularExpression Id. */
  int COMMA = 12;
  /** RegularExpression Id. */
  int QUERY = 13;
  /** RegularExpression Id. */
  int LPAREN = 14;
  /** RegularExpression Id. */
  int RPAREN = 15;
  /** RegularExpression Id. */
  int LBRACK = 16;
  /** RegularExpression Id. */
  int RBRACK = 17;
  /** RegularExpression Id. */
  int LBRACE = 18;
  /** RegularExpression Id. */
  int RBRACE = 19;
  /** RegularExpression Id. */
  int SEMI = 20;
  /** RegularExpression Id. */
  int DOT = 21;
  /** RegularExpression Id. */
  int TILDA = 22;
  /** RegularExpression Id. */
  int CARAT = 23;
  /** RegularExpression Id. */
  int NONTERMINAL = 24;
  /** RegularExpression Id. */
  int HEX = 25;
  /** RegularExpression Id. */
  int UCHAR = 26;
  /** RegularExpression Id. */
  int UCHAR4 = 27;
  /** RegularExpression Id. */
  int UCHAR8 = 28;
  /** RegularExpression Id. */
  int QUOTED_STRING = 29;
  /** RegularExpression Id. */
  int QSTRING1 = 30;
  /** RegularExpression Id. */
  int QSTRING2 = 31;
  /** RegularExpression Id. */
  int AZ = 32;
  /** RegularExpression Id. */
  int DIGITS = 33;
  /** RegularExpression Id. */
  int INTEGER = 34;
  /** RegularExpression Id. */
  int AZN = 35;
  /** RegularExpression Id. */
  int HEX_CHAR = 36;
  /** RegularExpression Id. */
  int CHAR_RANGE = 37;
  /** RegularExpression Id. */
  int WORD = 38;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<LINE_COMMENT>",
    "\"/*\"",
    "<token of kind 3>",
    "\"*/\"",
    "<WSP>",
    "<EOL>",
    "\"::=\"",
    "\"|\"",
    "\"*\"",
    "\"+\"",
    "\"-\"",
    "\",\"",
    "\"?\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\".\"",
    "\"~\"",
    "\"^\"",
    "<NONTERMINAL>",
    "<HEX>",
    "<UCHAR>",
    "<UCHAR4>",
    "<UCHAR8>",
    "<QUOTED_STRING>",
    "<QSTRING1>",
    "<QSTRING2>",
    "<AZ>",
    "<DIGITS>",
    "<INTEGER>",
    "<AZN>",
    "<HEX_CHAR>",
    "<CHAR_RANGE>",
    "<WORD>",
  };

}
