/* EBNFParser.java */
/* Generated By:JavaCC: Do not edit this line. EBNFParser.java */
package org.seaborne.bnf.parser.javacc;

import org.seaborne.bnf.parser.*;
import org.seaborne.bnf.ast.*;

public class EBNFParser extends BNFParser implements EBNFParserConstants {

  final public void Unit() throws ParseException {
    Grammar();
}

  final public void EOL() throws ParseException {
    jj_consume_token(EOL);
}

  final public void Grammar() throws ParseException {Rule rule;
    BlankLines();
startGrammar();
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case NONTERMINAL:
      case CHAR_RANGE:
      case WORD:{
        ;
        break;
        }
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      rule = Rule();
emitRule(rule);
      BlankLines();
    }
    jj_consume_token(0);
finishGrammar();
}

  final public Rule Rule() throws ParseException {Identifier identifier ; Expression expr; Rule rule; String label = null;
startRule();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case CHAR_RANGE:{
      label = Label();
      break;
      }
    default:
      jj_la1[1] = jj_gen;
      ;
    }
    identifier = Identifier();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case EOL:{
      jj_consume_token(EOL);
      break;
      }
    default:
      jj_la1[2] = jj_gen;
      ;
    }
    jj_consume_token(ASSIGN);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case EOL:{
      jj_consume_token(EOL);
      break;
      }
    default:
      jj_la1[3] = jj_gen;
      ;
    }
    expr = Expression();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case EOL:{
      EOL();
      break;
      }
    case 0:{
      jj_consume_token(0);
      break;
      }
    default:
      jj_la1[4] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
rule = createRule(label, identifier, expr);
      finishRule();
{if ("" != null) return rule;}
    throw new Error("Missing return statement in function");
}

// Bad name if used for EOL.
  final public void BlankLines() throws ParseException {
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case EOL:{
        ;
        break;
        }
      default:
        jj_la1[5] = jj_gen;
        break label_2;
      }
      EOL();
    }
}

  final public String Label() throws ParseException {String str = ""; Token t;
    // Hack fix.
         t = jj_consume_token(CHAR_RANGE);
str = removeOuter(t.image);
{if ("" != null) return str;}
    throw new Error("Missing return statement in function");
}

// LHS
  final public Identifier Identifier() throws ParseException {Token t; String str;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case NONTERMINAL:{
      t = jj_consume_token(NONTERMINAL);
{if ("" != null) return createNonTerminal(t.image);}
      break;
      }
    case WORD:{
      str = Word();
{if ("" != null) return createWord(str);}
      break;
      }
    default:
      jj_la1[6] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  final public Expression Expression() throws ParseException {Expression expr;
startExpression() ;
    expr = Alternatives();
finishExpression() ;
{if ("" != null) return expr;}
    throw new Error("Missing return statement in function");
}

  final public Expression Alternatives() throws ParseException {Expression expr ;
startAlternatives() ;
    expr = Sequence();
emitAlternativesElement(expr);
    label_3:
    while (true) {
      if (jj_2_1(2)) {
        ;
      } else {
        break label_3;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case EOL:{
        jj_consume_token(EOL);
        break;
        }
      default:
        jj_la1[7] = jj_gen;
        ;
      }
      jj_consume_token(OR);
      expr = Sequence();
emitAlternativesElement(expr);
    }
expr = collectedAlternatives();
finishAlternatives() ;
{if ("" != null) return expr;}
    throw new Error("Missing return statement in function");
}

  final public Expression Minus(Expression LHS) throws ParseException {Expression RHS , expr;
startMinus();
    jj_consume_token(MINUS);
    //    RHS = Expression()
        RHS = Primary();
expr = createMinusElement(LHS, RHS);
finishMinus();
{if ("" != null) return expr;}
    throw new Error("Missing return statement in function");
}

// At least one element.
  final public Expression Sequence() throws ParseException {Expression expr;
startSequence() ;
    label_4:
    while (true) {
      // Maybe Minus()
            expr = Unary();
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MINUS:{
        expr = Minus(expr);
        break;
        }
      default:
        jj_la1[8] = jj_gen;
        ;
      }
emitSequenceElement(expr);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case LPAREN:
      case NONTERMINAL:
      case QUOTED_STRING:
      case HEX_CHAR:
      case CHAR_RANGE:
      case WORD:{
        ;
        break;
        }
      default:
        jj_la1[9] = jj_gen;
        break label_4;
      }
    }
expr = collectedSequence();
      finishSequence() ;
      {if ("" != null) return expr;}
    throw new Error("Missing return statement in function");
}

  final public Expression Unary() throws ParseException {Expression expr; Token mod = null;
    expr = Primary();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case STAR:
    case PLUS:
    case QUERY:
    case LBRACE:{
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case QUERY:{
        jj_consume_token(QUERY);
expr = createExprZeroOrOne(expr);
        break;
        }
      case STAR:{
        jj_consume_token(STAR);
expr = createExprZeroOrMore(expr);
        break;
        }
      case PLUS:{
        jj_consume_token(PLUS);
expr = createExprOneOrMore(expr);
        break;
        }
      case LBRACE:{
        expr = Repeat(expr);
        break;
        }
      default:
        jj_la1[10] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
      }
    default:
      jj_la1[11] = jj_gen;
      ;
    }
{if ("" != null) return expr;}
    throw new Error("Missing return statement in function");
}

  final public Expression Repeat(Expression expr) throws ParseException {String str1 = null; String str2 = null;
    jj_consume_token(LBRACE);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case STAR:
    case INTEGER:{
      str1 = RepeatCount();
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case COMMA:{
        jj_consume_token(COMMA);
str2 = "";
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case STAR:
        case INTEGER:{
          str2 = RepeatCount();
          break;
          }
        default:
          jj_la1[12] = jj_gen;
          ;
        }
        break;
        }
      default:
        jj_la1[13] = jj_gen;
        ;
      }
      break;
      }
    case COMMA:{
      jj_consume_token(COMMA);
str1 = "";
      str2 = RepeatCount();
      break;
      }
    default:
      jj_la1[14] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    jj_consume_token(RBRACE);
{if ("" != null) return createExprRepeat(expr, str1, str2);}
    throw new Error("Missing return statement in function");
}

  final public String RepeatCount() throws ParseException {Token t; String str;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case STAR:{
      t = jj_consume_token(STAR);
{if ("" != null) return t.image;}
      break;
      }
    case INTEGER:{
      str = Integer();
{if ("" != null) return str;}
      break;
      }
    default:
      jj_la1[15] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  final public Expression Primary() throws ParseException {String str; Token t; Expression expr;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case NONTERMINAL:{
      t = jj_consume_token(NONTERMINAL);
{if ("" != null) return createNonTerminal(t.image);}
      break;
      }
    case WORD:{
      str = Word();
{if ("" != null) return createWord(str);}
      break;
      }
    case QUOTED_STRING:{
      t = jj_consume_token(QUOTED_STRING);
{if ("" != null) return createQuotedString(t.image);}
      break;
      }
    case LPAREN:{
      jj_consume_token(LPAREN);
      expr = Expression();
      jj_consume_token(RPAREN);
{if ("" != null) return createPrimary(expr);}
      break;
      }
    case HEX_CHAR:{
      expr = Character();
{if ("" != null) return expr;}
      break;
      }
    case CHAR_RANGE:{
      expr = CharacterRange();
{if ("" != null) return expr;}
      break;
      }
    default:
      jj_la1[16] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  final public Expression Character() throws ParseException {Token t;
    t = jj_consume_token(HEX_CHAR);
{if ("" != null) return createCharacter(t.image);}
    throw new Error("Missing return statement in function");
}

  final public Expression CharacterRange() throws ParseException {Token t;
    // Spaces are significant.
        // Capture here as the "[....]"
        // and parse the token in detail.
    
        t = jj_consume_token(CHAR_RANGE);
{if ("" != null) return createCharacterRange(t.image);}
    throw new Error("Missing return statement in function");
}

// Expression CharacterRange() : { String s1; String s2; boolean isNegative = false; }
// {
//     // Spaces are significant.
//     // Capture here as the "[....]"
//     // and parse the 
// 
//     <LBRACK>
//     ( <CARAT> { isNegative = true; } )?
//     s1 = RangeElement()
//     "-"
//     s2 = RangeElement()
//     <RBRACK>
//     { return createCharacterRange(s1, s2, isNegative); }
// }
// 
// String RangeElement() : { String str; }
// {
//   ( str = HexChar() { return str; }
//   // later: Parse lexical state to switch to a different set of lexical tokens
//   | str = Word()   { return wordToRangeChar(str, token.beginLine, token.beginColumn); }
//   | str = Integer()  { return wordToRangeChar(str, token.beginLine, token.beginColumn); }
//   )
// }
//
// String HexChar() : { Token t; String str; }
// {
//     t = <HEX_CHAR>
//     { return t.image; }
// }

// Abstract away from the concrete token.

// String WS() : { }
// {
// }
  final public 
String Word() throws ParseException {Token t; String str;
    t = jj_consume_token(WORD);
{if ("" != null) return t.image;}
    throw new Error("Missing return statement in function");
}

  final public String Integer() throws ParseException {Token t; String str;
    t = jj_consume_token(INTEGER);
{if ("" != null) return t.image;}
    throw new Error("Missing return statement in function");
}

  private boolean jj_2_1(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_1()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_3R_CharacterRange_291_5_17()
 {
    if (jj_scan_token(CHAR_RANGE)) return true;
    return false;
  }

  private boolean jj_3R_Primary_266_7_12()
 {
    if (jj_scan_token(LPAREN)) return true;
    return false;
  }

  private boolean jj_3R_Unary_220_5_7()
 {
    if (jj_3R_Primary_259_5_8()) return true;
    return false;
  }

  private boolean jj_3R_Primary_264_7_11()
 {
    if (jj_scan_token(QUOTED_STRING)) return true;
    return false;
  }

  private boolean jj_3R_Word_333_5_15()
 {
    if (jj_scan_token(WORD)) return true;
    return false;
  }

  private boolean jj_3R_Primary_262_7_10()
 {
    if (jj_3R_Word_333_5_15()) return true;
    return false;
  }

  private boolean jj_3R_Primary_260_7_9()
 {
    if (jj_scan_token(NONTERMINAL)) return true;
    return false;
  }

  private boolean jj_3R_Primary_259_5_8()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_Primary_260_7_9()) {
    jj_scanpos = xsp;
    if (jj_3R_Primary_262_7_10()) {
    jj_scanpos = xsp;
    if (jj_3R_Primary_264_7_11()) {
    jj_scanpos = xsp;
    if (jj_3R_Primary_266_7_12()) {
    jj_scanpos = xsp;
    if (jj_3R_Primary_274_7_13()) {
    jj_scanpos = xsp;
    if (jj_3R_Primary_276_7_14()) return true;
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_Character_282_4_16()
 {
    if (jj_scan_token(HEX_CHAR)) return true;
    return false;
  }

  private boolean jj_3R_Primary_276_7_14()
 {
    if (jj_3R_CharacterRange_291_5_17()) return true;
    return false;
  }

  private boolean jj_3R_Sequence_207_7_6()
 {
    if (jj_3R_Unary_220_5_7()) return true;
    return false;
  }

  private boolean jj_3R_Primary_274_7_13()
 {
    if (jj_3R_Character_282_4_16()) return true;
    return false;
  }

  private boolean jj_3_1()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(6)) jj_scanpos = xsp;
    if (jj_scan_token(OR)) return true;
    if (jj_3R_Sequence_204_5_5()) return true;
    return false;
  }

  private boolean jj_3R_Sequence_204_5_5()
 {
    Token xsp;
    if (jj_3R_Sequence_207_7_6()) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_Sequence_207_7_6()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  /** Generated Token Manager. */
  public EBNFParserTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  private int jj_gen;
  final private int[] jj_la1 = new int[17];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0x800000,0x0,0x40,0x40,0x41,0x40,0x800000,0x40,0x800,0x10804000,0x42600,0x42600,0x200,0x1000,0x1200,0x200,0x10804000,};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {0x30,0x10,0x0,0x0,0x0,0x0,0x20,0x0,0x0,0x38,0x0,0x0,0x2,0x0,0x2,0x2,0x38,};
	}
  final private JJCalls[] jj_2_rtns = new JJCalls[1];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with InputStream. */
  public EBNFParser(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public EBNFParser(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new EBNFParserTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 17; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 17; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public EBNFParser(java.io.Reader stream) {
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new EBNFParserTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 17; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new EBNFParserTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 17; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public EBNFParser(EBNFParserTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 17; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(EBNFParserTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 17; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   if (++jj_gc > 100) {
		 jj_gc = 0;
		 for (int i = 0; i < jj_2_rtns.length; i++) {
		   JJCalls c = jj_2_rtns[i];
		   while (c != null) {
			 if (c.gen < jj_gen) c.first = null;
			 c = c.next;
		   }
		 }
	   }
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }

  @SuppressWarnings("serial")
  static private final class LookaheadSuccess extends java.lang.Error {
    @Override
    public Throwable fillInStackTrace() {
      return this;
    }
  }
  static private final LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
	 if (jj_scanpos == jj_lastpos) {
	   jj_la--;
	   if (jj_scanpos.next == null) {
		 jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
	   } else {
		 jj_lastpos = jj_scanpos = jj_scanpos.next;
	   }
	 } else {
	   jj_scanpos = jj_scanpos.next;
	 }
	 if (jj_rescan) {
	   int i = 0; Token tok = token;
	   while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
	   if (tok != null) jj_add_error_token(kind, i);
	 }
	 if (jj_scanpos.kind != kind) return true;
	 if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
	 return false;
  }


/** Get the next Token. */
  final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
	 if (pos >= 100) {
		return;
	 }

	 if (pos == jj_endpos + 1) {
	   jj_lasttokens[jj_endpos++] = kind;
	 } else if (jj_endpos != 0) {
	   jj_expentry = new int[jj_endpos];

	   for (int i = 0; i < jj_endpos; i++) {
		 jj_expentry[i] = jj_lasttokens[i];
	   }

	   for (int[] oldentry : jj_expentries) {
		 if (oldentry.length == jj_expentry.length) {
		   boolean isMatched = true;

		   for (int i = 0; i < jj_expentry.length; i++) {
			 if (oldentry[i] != jj_expentry[i]) {
			   isMatched = false;
			   break;
			 }

		   }
		   if (isMatched) {
			 jj_expentries.add(jj_expentry);
			 break;
		   }
		 }
	   }

	   if (pos != 0) {
		 jj_lasttokens[(jj_endpos = pos) - 1] = kind;
	   }
	 }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[38];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 17; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 38; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 jj_endpos = 0;
	 jj_rescan_token();
	 jj_add_error_token(0, 0);
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  private boolean trace_enabled;

/** Trace enabled. */
  final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

  private void jj_rescan_token() {
	 jj_rescan = true;
	 for (int i = 0; i < 1; i++) {
	   try {
		 JJCalls p = jj_2_rtns[i];

		 do {
		   if (p.gen > jj_gen) {
			 jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
			 switch (i) {
			   case 0: jj_3_1(); break;
			 }
		   }
		   p = p.next;
		 } while (p != null);

		 } catch(LookaheadSuccess ls) { }
	 }
	 jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
	 JJCalls p = jj_2_rtns[index];
	 while (p.gen > jj_gen) {
	   if (p.next == null) { p = p.next = new JJCalls(); break; }
	   p = p.next;
	 }

	 p.gen = jj_gen + xla - jj_la; 
	 p.first = token;
	 p.arg = xla;
  }

  static final class JJCalls {
	 int gen;
	 Token first;
	 int arg;
	 JJCalls next;
  }

                                           }
