/* Generated By:JavaCC: Do not edit this line. EBNFParserConstants.java */
package org.seaborne.bnf.parser.javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface EBNFParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LINE_COMMENT = 1;
  /** RegularExpression Id. */
  int WSP = 2;
  /** RegularExpression Id. */
  int LF = 3;
  /** RegularExpression Id. */
  int CR = 4;
  /** RegularExpression Id. */
  int EOL = 5;
  /** RegularExpression Id. */
  int ASSIGN = 6;
  /** RegularExpression Id. */
  int OR = 7;
  /** RegularExpression Id. */
  int STAR = 8;
  /** RegularExpression Id. */
  int PLUS = 9;
  /** RegularExpression Id. */
  int QUERY = 10;
  /** RegularExpression Id. */
  int LPAREN = 11;
  /** RegularExpression Id. */
  int RPAREN = 12;
  /** RegularExpression Id. */
  int LBRACK = 13;
  /** RegularExpression Id. */
  int RBRACK = 14;
  /** RegularExpression Id. */
  int LBRACE = 15;
  /** RegularExpression Id. */
  int RBRACE = 16;
  /** RegularExpression Id. */
  int SEMI = 17;
  /** RegularExpression Id. */
  int DOT = 18;
  /** RegularExpression Id. */
  int NONTERMINAL = 19;
  /** RegularExpression Id. */
  int ECHAR = 20;
  /** RegularExpression Id. */
  int HEX = 21;
  /** RegularExpression Id. */
  int UCHAR = 22;
  /** RegularExpression Id. */
  int UCHAR4 = 23;
  /** RegularExpression Id. */
  int UCHAR8 = 24;
  /** RegularExpression Id. */
  int QUOTED_STRING = 25;
  /** RegularExpression Id. */
  int QSTRING1 = 26;
  /** RegularExpression Id. */
  int QSTRING2 = 27;
  /** RegularExpression Id. */
  int AZ = 28;
  /** RegularExpression Id. */
  int DIGITS = 29;
  /** RegularExpression Id. */
  int INTEGER = 30;
  /** RegularExpression Id. */
  int AZN = 31;
  /** RegularExpression Id. */
  int HEX_CHAR = 32;
  /** RegularExpression Id. */
  int WORD = 33;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<LINE_COMMENT>",
    "<WSP>",
    "\"\\r\"",
    "\"\\n\"",
    "<EOL>",
    "\"::=\"",
    "\"|\"",
    "\"*\"",
    "\"+\"",
    "\"?\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\".\"",
    "<NONTERMINAL>",
    "<ECHAR>",
    "<HEX>",
    "<UCHAR>",
    "<UCHAR4>",
    "<UCHAR8>",
    "<QUOTED_STRING>",
    "<QSTRING1>",
    "<QSTRING2>",
    "<AZ>",
    "<DIGITS>",
    "<INTEGER>",
    "<AZN>",
    "<HEX_CHAR>",
    "<WORD>",
    "\"-\"",
  };

}
